# Generated by Django 3.1.6 on 2022-01-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='', max_length=50)),
                ('motivo', models.CharField(default='', max_length=1000)),
                ('data_registro', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
