# Generated by Django 3.1.6 on 2022-01-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='motivo',
            new_name='mensagem',
        ),
    ]
