# Generated by Django 3.1.6 on 2022-01-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220130_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='group',
            field=models.CharField(default='', max_length=50),
        ),
    ]
